apiVersion: apps/v1
kind: Deplyment
metadata:
  name: microservicio-java-deployment
  labels:
    app: microservicio-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservicio-java
  template:
    metadata:
      labels:
        app: microservicio-java
    spec:
      containers:
        - name: microservicio-java
          image: wladimirluna/microservicio-java:latest
          ports:
            - containerPort: 8085
