name: CI
on:
  
 push:
 workflow_dispatch:
 
jobs:
  
 build:
   
  runs-on: ubuntu-latest
  
  steps:
   
   - uses: actions/checkout@v3
   
   # Runs a set of commands using the runners shell
   - name: Build
     run: |
      chmod +x gradlew
      ./gradlew build
      cd ./build
      ls -ltr
      
   - name: SonarCloud Analysis
     run: |
       chmod +x gradlew
       ./gradlew build sonar -Dsonar.token=${{ secrets.MICROSERVICIO_JAVA_SECRET }}

   - name: Docker Login
     uses: docker/login-action@v2.2.0
     with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}

   - name: Docker Build
     run: |
      docker build --tag wladimirluna/microservicio-java:latest .
      docker images

   - name: Docker Push
     run: |
       docker push wladimirluna/microservicio-java
     
