name: CI
on:
  
 push:
 workflow_dispatch:
 
jobs:
  
 build:
   
  runs-on: ubuntu-latest
  
  steps:
   
   - uses: actions/checkout@v3
   
   # Runs a set of commands using the runners shell
   - name: Build
     run: |
      chmod +x gradlew
      ./gradlew build
      cd ./build
      ls -ltr

   - name: UnitTest
     run: |
      chmod +x gradlew
      ./gradlew test
      
   - name: SonarCloud Analysis
     run: |
       chmod +x gradlew
       ./gradlew build sonar -Dsonar.token=${{ secrets.MICROSERVICIO_JAVA_SECRET }}

   - name: Docker Login
     uses: docker/login-action@v2.2.0
     with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}

   - name: Copia de jar a raiz de proyecto
     run: |
       cp $GITHUB_WORKSPACE/build/libs/microservicio-java-2.6.0.jar .
       chmod 777 microservicio-java-2.6.0.jar
       ls -lt
       
   - name: Docker Build
     run: |
      docker build --tag wladimirluna/microservicio-java:latest .
      docker images

   - name: Docker Push
     run: |
       docker push wladimirluna/microservicio-java
     
 deploy:

    runs-on: self-hosted
    needs: build  
    steps:

      - uses: actions/checkout@v3

      - name: Deploy to Minikube
        run: |
          echo "Iniciando despliegue en Kubernetes"
          kubectl apply -f deployment.yml

 acceptanceTests:

  runs-on: self-hosted
  needs: deploy
  steps:

    - uses: actions/checkout@v3

    - name: Postman
      run: |
        run microservicio-java.postman_collection.json
    
